# Generated by Django 3.0.8 on 2020-07-25 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vtb_name', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=128)),
                ('group', models.CharField(max_length=128)),
                ('url', models.URLField()),
                ('version', models.CharField(max_length=20)),
                ('count', models.IntegerField()),
                ('update_time', models.DateTimeField()),
                ('translate', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='VoiceGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vtb_name', models.CharField(max_length=128)),
                ('group_name', models.CharField(max_length=128)),
                ('all_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vtuber',
            fields=[
                ('name', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('bilibili_uid', models.IntegerField()),
                ('youtube_id', models.CharField(max_length=128)),
            ],
        ),
    ]
