# Generated by Django 3.0.8 on 2020-07-25 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataBaseModel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voicegroup',
            name='translate',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='voice',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
